# AirGradient Pro V3.3 - V4.2
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: "ag-pro"
  friendly_name: "AG Pro"
  name_add_mac_suffix: "false"  # Должно быть в кавычках

# Включение API Home Assistant с шифрованием и ограничением частоты запросов
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 15min
  services:
    - service: restart
      then:
        - delay: 5s
        - restart: soft

# Обновление по воздуху с защитой паролем
ota:
  platform: esphome
  password: !secret ota_password
  safe_mode: true
  num_attempts: 10

# Настройка WiFi с автоматическим переподключением и резервной точкой доступа
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  reboot_timeout: 15min
  
  # Настройка резервной точки доступа
  ap:
    ssid: "${friendly_name} Резервная точка"
    password: !secret wifi_ap_password

# Включение логирования с ротацией
logger:
  level: INFO
  baud_rate: 0
  logs:
    max_message_length: 150
    queue_size: 25

# Веб-сервер отключен для экономии ресурсов на ESP8266
# web_server:
#   port: 80
#   auth:
#     username: !secret web_username
#     password: !secret web_password

dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-pro.yaml
  import_full_config: false

# Мониторинг системы
sensor:
  - platform: wifi_signal
    name: "${friendly_name} Сигнал WiFi"
    update_interval: 60s
    id: wifi_signal
  - platform: free_heap
    name: "${friendly_name} Свободная память"
    update_interval: 60s
    id: free_heap

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_d1_mini_board.yaml
  captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht40.yaml
  # temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht30.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://MallocArray/airgradient_esphome/packages/display_sh1106_single_page.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_d1_mini.yaml
  config_button: github://MallocArray/airgradient_esphome/packages/config_button.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml

binary_sensor:
  - platform: gpio
    id: config_button
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: "${friendly_name} Кнопка настройки"
    on_press:
      then:
        - logger.log: "Нажата кнопка настройки"
        - homeassistant.service:
            service: homeassistant.restart

# Автоматизация для защиты системы
automation:
  - trigger:
      platform: free_heap
      below: 4096  # 4KB свободной памяти
    then:
      - logger.log: "Обнаружена нехватка памяти, перезагрузка"
      - delay: 5s
      - restart: soft
